trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'                 # Uses default pom.xml
    mavenOptions: '-Xmx3072m'               # Keeps memory config
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'             # Uses agent's default JDK
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'verify'                         # Changed from 'package' to 'verify' (more standard for CI)



